CREATE TABLE CAR_INFO(
	MODEL_NUM INT PRIMARY KEY AUTO_INCREMENT #모델번호
	, MODEL_NAME VARCHAR(50) NOT NULL #모델명
	, CAR_PRICE INT NOT NULL  #금액
	, MANUFACTURER VARCHAR(30) NOT NULL #제조사
);

select * from car_info;

CREATE TABLE SALES_INFO(
	SALES_NUM INT PRIMARY KEY AUTO_INCREMENT #판매번호
	, SALES_NAME VARCHAR(30) NOT NULL #구매자명
	, SALES_TEL VARCHAR(20) #구매자 연락처
	, SALES_COLOR VARCHAR(20) NOT NULL #색상
	, SALES_DATE DATETIME DEFAULT SYSDATE() #판매일
	, MODEL_NUM INT NOT NULL REFERENCES CAR_INFO(MODEL_NUM) #모델번호(FK)
);

select * from sales_info;  

select SALES_NAME, SALES_TEL, SALES_DATE, SALES_COLOR, MODEL_NAME, CAR_PRICE, C.MODEL_NUM
  from car_info C inner join SALES_INFO S
    on C.MODEL_NUM  = S.MODEL_NUM
 order by SALES_DATE desc;
  

